<template>
  <svg
    width="30"
    height="30"
    viewBox="0 0 30 30"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle
      cx="15"
      cy="15"
      r="14"
      stroke="#1BAA75"
      stroke-width="2"
    />
    <circle
      cx="15"
      cy="15"
      r="10"
      fill="#1BAA75"
    />
  </svg>
</template>
